ekf_localization_node:
  # IMU Configuration
  imu0: imu/data
  imu0_config: [false, false, false,
                true,  true,  true,
                false, false, false,
                false, false, false,
                false, false, false]
  imu0_differential: false
  imu0_queue_size: 10
  imu0_remove_gravitational_acceleration: true

  # Odom Configuration
  odom0: odom_data_quat
  odom0_config: [true,  true,  false,
                 false, false, false,
                 true,  true,  false,
                 false, false, false]
  odom0_differential: false
  odom0_queue_size: 10
  
  
  

  # Other settings
  use_control: false
  print_diagnostics: true
  publish_tf: true
  map_frame: map
  odom_frame: odom
  base_link_frame: base_link
  world_frame: world
